services:
  postgres:
    image: postgres:18
    container_name: devhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: devhub
      POSTGRES_USER: devhub
      POSTGRES_PASSWORD: devhub123
    ports:
      - "5432:5432"
    volumes:
      - devhub_postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  devhub_postgres_data:
