spring.application.name=DevHub Backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/devhub
spring.datasource.username=devhub
spring.datasource.password=devhub123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
